# This is just a dummy entry (the `x-yaml-aliases` key is not an official pipeline key, and will be ignored by BuildKite)
# that we use only to store YAML anchors (`&xxx`), that we plan to use and reference later in the YAML file (using `*xxx`)
# without having to copy/paste the same values over and over.
# Note: keys like `agent`, `env`, … used here are totally arbitrary; the only point is to define various separate `&xxx` anchors there.
#
x-yaml-aliases:
  agent: &macos
    queue: "macos"
    git: "github"
  env: &env
    FASTLANE_SKIP_UPDATE_CHECK: 1
  conditions:
    - &release_branch |
      // Only on PR builds, and for branches starting with 'release/'
      build.branch =~ /^release\// &&
        build.env("NIGHTLY_BUILD") == null
    - &feature_branch |
      // Only on PR builds, and for branches other than 'develop', 'master', and 'release/*'
      build.branch != 'master' &&
        build.branch != 'develop' &&
        build.branch !~ /^release\// &&
        build.env("NIGHTLY_BUILD") == null
    - &nightly |
      // Only for nightly builds
      build.env("NIGHTLY_BUILD") != null
  commands:
    - &setup |
      echo --- Setup
      brew install cmake
      bundle install
      printf %100s\\n | tr ' ' '='
    - &pod_lint |
      echo --- pod lib lint
      # MatrixKit-*.podspec and MatrixSDK-*.pospec are created by the `bundle exec fastlane point_podspec_to_…` lanes supposed to be run beforehand
      #=== Use '--quick' mode for now until we have better CI machines than our MacMini ===
      bundle exec pod lib lint local-podspecs/MatrixKit.podspec --verbose --allow-warnings --external-podspecs=local-podspecs/MatrixSDK.podspec --quick
      # bundle exec pod lib lint local-podspecs/MatrixKit.podspec --verbose --allow-warnings --external-podspecs=local-podspecs/MatrixSDK.podspec
    - &build_sample_app |
      echo --- fastlane build_sample_app
      bundle exec fastlane build_sample_app

################################################################################

steps:

  ###### Steps for Release Branches ######

  - label: "Release: Lint Pod"
    agents: *macos
    if: *release_branch
    env: *env
    commands:
      - *setup
      - echo --- Point podspec to pending release
      - bundle exec fastlane point_podspec_to_pending_releases
      - *pod_lint

  - label: "Release: Build Sample App"
    agents: *macos
    if: *release_branch
    env: *env
    commands:
      - *setup
      - echo --- Point sample app to pending release
      - bundle exec fastlane point_sample_app_to_pending_releases
      - *build_sample_app

  ###### Steps for Feature Branches ######

  - label: "Feature: Lint Pod"
    agents: *macos
    if: *feature_branch
    env: *env
    commands:
      - *setup
      - echo --- Point podspec to same feature branch
      - bundle exec fastlane point_podspec_to_same_feature
      - *pod_lint

  - label: "Feature: Build Sample App"
    agents: *macos
    if: *feature_branch
    env: *env
    commands:
      - *setup
      - echo --- Point sample app to same feature branch
      - bundle exec fastlane point_sample_app_to_same_feature
      - *build_sample_app
