version: '3.1'

services:

  postgres:
    image: postgres:9.5
    environment:
      POSTGRES_PASSWORD: postgres
    command: -c fsync=off

  testenv:
    image: python:3.5
    depends_on:
      - postgres
    env_file: .env
    environment:
      SYNAPSE_POSTGRES_HOST: postgres
      SYNAPSE_POSTGRES_USER: postgres
      SYNAPSE_POSTGRES_PASSWORD: postgres
    working_dir: /src
    volumes:
      - ..:/src
