steps:
  - command:
      - "python -m pip install tox"
      - "tox -e pep8"
    label: "Check Code Style"
    plugins:
      - docker#v3.0.1:
          image: "python:3.5"
          mount-buildkite-agent: false

  - command:
      - "python -m pip install tox"
      - "tox -e packaging"
    label: "Check Packaging"
    plugins:
      - docker#v3.0.1:
          image: "python:3.5"
          mount-buildkite-agent: false

  - wait

  - command:
      - "python -m pip install tox"
      - "tox -e py35"
    label: ":python: 3.5 — Unit tests"
    plugins:
      - docker#v3.0.1:
          image: "python:3.5"
          mount-buildkite-agent: false

  - command:
      - "python -m pip install tox"
      - "tox -e py36"
    label: ":python: 3.6 — Unit tests"
    plugins:
      - docker#v3.0.1:
          image: "python:3.6"
          mount-buildkite-agent: false

  - command:
      - "python -m pip install tox"
      - "tox -e py37"
    label: ":python: 3.7 — Unit tests"
    plugins:
      - docker#v3.0.1:
          image: "python:3.7"
          mount-buildkite-agent: false

  - command:
      - "python -m pip install tox"
      - "tox -e py38"
    label: ":python: 3.8 — Unit tests"
    plugins:
      - docker#v3.0.1:
          image: "python:3.8"
          mount-buildkite-agent: false
