# Use Docker file from https://hub.docker.com/r/runmymind/docker-android-sdk

steps:      
  - label: "Setup RubyGems Home"
    agents: &macos
      queue: "macos"
      git: "github"
    commands:
      - env
      - echo $HOME
      - echo $USER
      - source ~$USER/.zshrc
      - env
      - gem env

  # Install RubyGems and CocoaPods libs
  - label: "Install Gems & Pods"
    agents: *macos
    commands:
      - bundle install
      - bundle exec pod install
      - ls .

  # - label: "Hello Develop"
  #   agents: *macos
  #   command: "echo Hello World from Develop or feature branch $BUILDKITE_BRANCH."
  #   branches: "develop feature/*"

  # - label: "Hello Master"
  #   agents: *macos
  #   command: "echo Hello World from Master branch."
  #   branches: "master"

  - label: "Dump CP env for debug"
    agents: *macos
    commands:
      - ls .
      - gem env
      - bundle exec pod env

  - label: "Fastlane Info"
    agents: *macos
    commands:
      - bundle exec fastlane lanes

  - label: "Xcode Info"
    agents: *macos
    command: 
      - xcodebuild -showBuildSettings

  - wait

  - label: "Good Bye"
    agents: *macos
    command: "echo All sync'd up."
