yaml_aliases:
  agent: &macos
    queue: "macos"
    git: "github"
  cache_scripts:
    - &save_pods_cache sh <<SAVE_CACHE
        CACHE_MANIFEST_FILE=Podfile.lock
        CACHE_PATH_TO_SAVE=Pods/

        checksum=\$(shasum \${CACHE_MANIFEST_FILE} | awk '{print \$1}')
        cachekey=v1-cache-\$checksum
        cachedir="/tmp/buildkite-agent-cache/\${BUILDKITE_ORGANIZATION_SLUG}/\${BUILDKITE_PIPELINE_SLUG}"
        mkdir -p "\${cachedir}/\${cachekey}"
        rsync -a --delete "\${CACHE_PATH_TO_SAVE}/" "\${cachedir}/\${cachekey}/\${CACHE_PATH_TO_SAVE}/"
      CACHE
    - &restore_pods_cache sh <<RESTORE_CACHE
        CACHE_MANIFEST_FILE=Podfile.lock

        checksum=\$(shasum \${CACHE_MANIFEST_FILE} | awk '{print \$1}')
        cachekey=v1-cache-\$checksum
        cachedir="/tmp/buildkite-agent-cache/\${BUILDKITE_ORGANIZATION_SLUG}/\${BUILDKITE_PIPELINE_SLUG}"
        mkdir -p "\${cachedir}/\${cachekey}"
        rsync -a "\${cache_prefix}/\${cache_key}/" .
      CACHE
  
steps:
  # Install RubyGems and CocoaPods libs
  - label: "Install Gems & Pods"
    key: setup-pods
    agents: *macos
    commands:
      - bundle install
      - bundle exec pod install
      - pwd
      - ls
      - ls Pods
      - *save_pods_cache


  - wait

  - label: "Dump CP env for debug"
    agents: *macos
    depends_on: setup-pods
    commands:
      - *restore_pods_cache
      - pwd
      - ls
      - echo "=== Gem Env"
      - gem env
      - echo "=== Pod Env"
      - bundle exec pod env

  - label: "Fastlane Info"
    agents: *macos
    commands:
      - bundle exec fastlane lanes

  - label: "Xcode Info"
    agents: *macos
    command: 
      - xcodebuild -showBuildSettings

  - wait

  - label: "Good Bye"
    agents: *macos
    command: "echo All sync'd up."
