yaml_aliases:
  agent: &macos
    queue: "macos"
    git: "github"
  cache:
    - &cached_pod_install
      "cache:v1.0.0":
        paths:
          - path: Pods
            manifest: Podfile.lock
            scopes: [manifest]
            post-cache-miss:
              - bundle exec pod install
  
steps:
  # Install RubyGems and CocoaPods libs
  - label: "Install Gems & Pods"
    key: setup-pods
    agents: *macos
    commands:
      - bundle install
      - bundle exec pod install
      - pwd
      - ls
      - ls Pods

  - wait

  - label: "Dump CP env for debug"
    agents: *macos
    depends_on: setup-pods
    plugins: *cached_pod_install
    commands:
      - pwd
      - ls
      - echo "=== Gem Env"
      - gem env
      - echo "=== Pod Env"
      - bundle exec pod env

  - label: "Fastlane Info"
    agents: *macos
    commands:
      - bundle exec fastlane lanes

  - label: "Xcode Info"
    agents: *macos
    command: 
      - xcodebuild -showBuildSettings

  - wait

  - label: "Good Bye"
    agents: *macos
    command: "echo All sync'd up."
