# Use Docker file from https://hub.docker.com/r/runmymind/docker-android-sdk

steps:
  - label: "Setup RubyGems Home"
    agents: &macos
      queue: "macos"
      git: "github"
    command:
      - source $HOME/.zshrc
      - env
      - gem env

  # Install RubyGems and CocoaPods libs
  - label: "Install Gems & Pods"
    agents: *macos
    command:
      - bundle install --path=./vendor/
      - bundle exec pod install

  - label: "Hello Develop"
    command: "echo Hello World from Develop or feature branch $BUILDKITE_BRANCH."
    branches: "develop feature/*"
    agents: *macos

  - label: "Hello Master"
    command: "echo Hello World from Master branch."
    branches: "master"
    agents: *macos

  - label: "Dump CP env for debug"
    command: "bundle exec pod env"
    agents: *macos

  - label: "Fastlane Info"
    command: "bundle exec fastlane lanes"
    agents: *macos

  - label: "Xcode Info"
    command: "xcodebuild -showBuildSettings"
    agents: *macos

  - wait

  - label: "Good Bye"
    command: "echo All sync'd up."
    agents: *macos
