yaml_aliases:
  agent: &macos
    queue: "macos"
    git: "github"
  
steps:
  ### Steps for Release Branches

  - label: "Release: Lint Pod"
    key: release-lint
    agents: *macos
    branches: "release/*/release"
    commands:
      - bundle install
      - bundle exec pod install
      - bundle exec fastlane lint_pods

  - label: "Release: Build iOS"
    key: release-build-ios
    agents: *macos
    branches: "release/*/release"
    commands:
      - bundle install
      - bundle exec pod install
      - bundle exec fastlane build_ios

  - label: "Release: Build macOS"
    key: release-build-macos
    agents: *macos
    branches: "release/*/release"
    commands:
      - bundle install
      - bundle exec pod install
      - bundle exec fastlane build_macos

  ### Steps for Feature Branches

  - label: "Feature: Lint Pod"
    key: feature-lint
    agents: *macos
    branches: "feature/*"
    commands:
      - bundle install
      - bundle exec pod install
      - bundle exec fastlane lint_pods

  - label: "Feature: Build iOS"
    key: feature-build-ios
    agents: *macos
    branches: "feature/*"
    commands:
      - bundle install
      - bundle exec pod install
      - bundle exec fastlane build_ios

  - label: "Feature: Build macOS"
    key: feature-build-macos
    agents: *macos
    branches: "feature/*"
    commands:
      - bundle install
      - bundle exec pod install
      - bundle exec fastlane build_macos
