# Use Docker file from https://hub.docker.com/r/runmymind/docker-android-sdk

steps:
  # Install RubyGems and CocoaPods libs
  - label: "Setup Gems & Pods"
    agents: &macos
      queue: "macOS"
    command:
      - gem install bundler
      - bundle install
      - bundle exec pod install

  - label: "Hello Develop"
    command: "echo Hello World from Develop or feature branch $BUILDKITE_BRANCH."
    branches: "develop feature/*"
    agents: *macos

  - label: "Hello Master"
    command: "echo Hello World from Master branch."
    branches: "master"
    agents: *macos

  - label: "Dump CP env for debug"
    command: "bundle exec pod env"
    agents: *macos

  - label: "Fastlane Info"
    command: "bundle exec fastlane lanes"
    agents: *macos

  - label: "Xcode Info"
    command: "xcodebuild -showBuildSettings"
    agents: *macos

  - wait

  - label: "Good Bye"
    command: "echo All sync'd up."
    agents: *macos
