# This is just a dummy entry (the `x-yaml-aliases` key is not an official pipeline key, and will be ignored by BuildKite)
#   that we use only to store YAML anchors (`&xxx`), that we plan to use and reference later in the YAML file (using `*xxx`)
#   without having to copy/paste the same values over and over.
#   Note: keys like `agent`, `env`, … used here are totally arbitrary; the only point is to define various separate `&xxx` anchors there.
#
x-yaml-aliases:
  agent: &macos
    queue: "macos"
    git: "github"
  env: &env
    FASTLANE_SKIP_UPDATE_CHECK: 1
  branches:
    - &release_branch "release/*/release"
    - &feature_branch "!master !develop !realease/*"
  commands:
    - &bundle_install
      bundle install
    - &pod_install
      bundle exec pod install
  
steps:
  ### Steps for Release Branches

  #=== Disable this one for now until we have better CI machines that our MacMini ===
  # - label: "Release: Lint Pod"
  #   agents: *macos
  #   branches: *release_branch
  #   env: *env
  #   commands:
  #     - *bundle_install
  #     - *pod_install
  #     - bundle exec fastlane lint_pods

  #=== Disable this one for now until we have better CI machines that our MacMini ===
  # - label: "Release: Build iOS"
  #   agents: *macos
  #   branches: *release_branch
  #   env: *env
  #   commands:
  #     - *bundle_install
  #     - *pod_install
  #     - bundle exec fastlane build_ios

  - label: "Release: Build macOS"
    agents: *macos
    branches: *release_branch
    env: *env
    commands:
      - *bundle_install
      - *pod_install
      - bundle exec fastlane build_macos

  ### Steps for Feature Branches

  #=== Disable this one for now until we have better CI machines that our MacMini ===
  # - label: "Feature: Lint Pod"
  #   agents: *macos
  #   branches: *feature_branch
  #   env: *env
  #   commands:
  #     - *bundle_install
  #     - *pod_install
  #     - bundle exec fastlane lint_pods

  #=== Disable this one for now until we have better CI machines that our MacMini ===
  # - label: "Feature: Build iOS"
  #   agents: *macos
  #   branches: *feature_branch
  #   env: *env
  #   commands:
  #     - *bundle_install
  #     - *pod_install
  #     - bundle exec fastlane build_ios

  - label: "Feature: Build macOS"
    agents: *macos
    branches: *feature_branch
    env: *env
    commands:
      - *bundle_install
      - *pod_install
      - bundle exec fastlane build_macos
