yaml_aliases:
  agent: &macos
    queue: "macos"
    git: "github"
  cache:
    - &save_pods_cache
      danthorpe/cache#v1.0.0:
        rsync_storage: '/tmp/buildkite-cache'
        cache_key: "v1-cache-{{ checksum 'Podfile.lock' }}"
        paths: [ "Pods/" ]
    - &restore_pods_cache
      danthorpe/cache#v1.0.0:
        rsync_storage: '/tmp/buildkite-cache'
        cache_key: "v1-cache-{{ checksum 'Podfile.lock' }}"

  
steps:
  # Install RubyGems and CocoaPods libs
  - label: "Install Gems & Pods"
    key: setup-pods
    agents: *macos
    commands:
      - bundle install
      - bundle exec pod install
      - pwd
      - ls
      - ls Pods
    plugins: # Save Cache
      - danthorpe/cache#v1.0.0:
          rsync_storage: '/tmp/buildkite-cache'
          cache_key: "v1-cache-{{ checksum 'Podfile.lock' }}"
          paths: [ "Pods/" ]

  - wait

  - label: "Dump CP env for debug"
    agents: *macos
    depends_on: setup-pods
    plugins: # Restore Cache
      - danthorpe/cache#v1.0.0:
          rsync_storage: '/tmp/buildkite-cache'
          cache_key: "v1-cache-{{ checksum 'Podfile.lock' }}"
    commands:
      - pwd
      - ls
      - echo "=== Download artefacts"
      - buildkite-agent artifact download Pods . --step setup-pods
      - echo "=== Post-artefact-download"
      - ls
      - echo "=== Gem Env"
      - gem env
      - bundle exec pod env

  - label: "Fastlane Info"
    agents: *macos
    commands:
      - bundle exec fastlane lanes

  - label: "Xcode Info"
    agents: *macos
    command: 
      - xcodebuild -showBuildSettings

  - wait

  - label: "Good Bye"
    agents: *macos
    command: "echo All sync'd up."
