steps:
  - label: ":eslint: Lint"
    command:
      - "yarn install"
      - "yarn lint"
    plugins:
      - docker#v3.0.1:
          image: "node:16"

  - label: ":nodejs: 14 :mocha: Unit/Integration Test"
    command:
      - "yarn install"
      - "yarn build"
      - "yarn test"
    plugins:
      - docker#v3.0.1:
          image: "node:14"

  - label: ":nodejs: 16 :mocha: Unit/Integration Test"
    command:
      - "yarn install"
      - "yarn build"
      - "yarn test"
    plugins:
      - docker#v3.0.1:
          image: "node:16"
