steps:
  - command:
      - "env"
      - "bash build.sh"
    label: "\U0001F528 Build / :go: 1.13"
    plugins:
      - docker#v3.0.1:
          image: "golang:1.13"
          mount-buildkite-agent: false
    retry:
      automatic:
        - exit_status: 128
          limit: 3
          
  - command:
      - "env"
      - "go test ./..."
    label: "\U0001F9EA Unit tests / :go: 1.13"
    plugins:
      - docker#v3.0.1:
          image: "golang:1.13"
          mount-buildkite-agent: false

  - wait

  - command:
      - "env"
      # https://github.com/golangci/golangci-lint#memory-usage-of-golangci-lint
      - "./build/scripts/find-lint.sh"
    label: "\U0001F9F9 Lint / :go: 1.13"
    agents:
      # Use a larger instance as linting takes a looot of memory
      queue: "xlarge"
    plugins:
      - docker#v3.0.1:
          image: "golang:1.13"
          mount-buildkite-agent: false
          
  - label: "SyTest - :go: 1.13 / :postgres: 9.6"
    agents:
      queue: "medium"
    env:
      POSTGRES: "1"
    command:
      - "bash /bootstrap.sh dendrite"
    plugins:
      - docker#v3.0.1:
          image: "matrixdotorg/sytest-dendrite"
          propagate-environment: true
          always-pull: true
          workdir: "/src"
          entrypoint: '/bin/sh'
          shell: ["-x", "-c"]
          init: false
          debug: true
          mount-buildkite-agent: false
          volumes: ["./logs:/logs"]
      - artifacts#v1.2.0:
          upload: [ "logs/**/*.log", "logs/**/*.log.*", "logs/results.tap" ]
      - matrix-org/annotate:
          path: "logs/annotate.md"
          style: "error"
    retry:
      automatic:
        - exit_status: -1
          limit: 2
        - exit_status: 2
          limit: 2
  
  - label: "SyTest - :go: 1.13 / :postgres: 9.6 / full HTTP APIs"
    agents:
      queue: "medium"
    env:
      POSTGRES: "1"
      API: "1"
    command:
      - "bash /bootstrap.sh dendrite"
    plugins:
      - docker#v3.0.1:
          image: "matrixdotorg/sytest-dendrite"
          propagate-environment: true
          always-pull: true
          workdir: "/src"
          entrypoint: '/bin/sh'
          shell: ["-x", "-c"]
          init: false
          debug: true
          mount-buildkite-agent: false
          volumes: ["./logs:/logs"]
      - artifacts#v1.2.0:
          upload: [ "logs/**/*.log", "logs/**/*.log.*", "logs/results.tap" ]
      - matrix-org/annotate:
          path: "logs/annotate.md"
          style: "error"
    retry:
      automatic:
        - exit_status: -1
          limit: 2
        - exit_status: 2
          limit: 2

  - label: "SyTest - :go: 1.13 / :sqlite: 3"
    agents:
      queue: "medium"
    command:
      - "bash /bootstrap.sh dendrite"
    plugins:
      - docker#v3.0.1:
          image: "matrixdotorg/sytest-dendrite"
          propagate-environment: true
          always-pull: true
          workdir: "/src"
          entrypoint: '/bin/sh'
          shell: ["-x", "-c"]
          init: false
          debug: true
          mount-buildkite-agent: false
          volumes: ["./logs:/logs"]
      - artifacts#v1.2.0:
          upload: [ "logs/**/*.log", "logs/**/*.log.*", "logs/results.tap" ]
      - matrix-org/annotate:
          path: "logs/annotate.md"
          style: "error"
    retry:
      automatic:
        - exit_status: -1
          limit: 2
        - exit_status: 2
          limit: 2

  - label: "SyTest - :go: 1.13 / :sqlite: 3 / full HTTP APIs"
    agents:
      queue: "medium"
    env:
      API: "1"
    command:
      - "bash /bootstrap.sh dendrite"
    plugins:
      - docker#v3.0.1:
          image: "matrixdotorg/sytest-dendrite"
          propagate-environment: true
          always-pull: true
          workdir: "/src"
          entrypoint: '/bin/sh'
          shell: ["-x", "-c"]
          init: false
          debug: true
          mount-buildkite-agent: false
          volumes: ["./logs:/logs"]
      - artifacts#v1.2.0:
          upload: [ "logs/**/*.log", "logs/**/*.log.*", "logs/results.tap" ]
      - matrix-org/annotate:
          path: "logs/annotate.md"
          style: "error"
    retry:
      automatic:
        - exit_status: -1
          limit: 2
        - exit_status: 2
          limit: 2
