steps:
  - label: ":eslint: Lint"
    command:
      # We fetch the develop js-sdk to get our latest eslint rules
      - "echo '--- Install js-sdk'"
      - "./scripts/ci/install-deps.sh --ignore-scripts"
      - "yarn lint"
    plugins:
      - docker#v3.0.1:
          image: "node:14-buster"
          # This allows the test script to see what branch it's testing and check
          # out the equivalent dependency branches, if they exist
          propagate-environment: true
          mount-buildkite-agent: false

  - label: ":globe_with_meridians: i18n"
    command:
      - "echo '--- Fetching Dependencies'"
      - "yarn install"
      - "echo '+++ Testing i18n output'"
      - "yarn diff-i18n"
    plugins:
      - docker#v3.0.1:
          image: "node:14-buster"
          mount-buildkite-agent: false
