steps:
  - label: ":eslint: Lint"
    command:
      - "yarn install"
      - "yarn lint"
    plugins:
      - docker#v3.0.1:
          image: "node:12"

  - label: ":nodejs: 12 Build"
    command:
      - "yarn install"
      - "yarn build"
    plugins:
      - docker#v3.0.1:
          image: "node:12"

  - label: ":nodejs: 10 Build"
    command:
      - "yarn install"
      - "yarn build"
    plugins:
      - docker#v3.0.1:
          image: "node:10"
