# This is just a dummy entry (the `x-yaml-aliases` key is not an official pipeline key, and will be ignored by BuildKite)
#   that we use only to store YAML anchors (`&xxx`), that we plan to use and reference later in the YAML file (using `*xxx`)
#   without having to copy/paste the same values over and over.
#   Note: keys like `agent`, `env`, … used here are totally arbitrary; the only point is to define various separate `&xxx` anchors there.
#
x-yaml-aliases:
  agent: &macos
    queue: "macos"
    git: "github"
  env: &env
    FASTLANE_SKIP_UPDATE_CHECK: 1
  branches:
    - &release_branch "release/*/release"
    - &feature_branch "!master !develop !realease/*"
  commands:
    - &setup |
      brew install cmake
      bundle install
      for n ({1..100}); do printf "="; done; print
    - &build_app
      bundle exec fastlane build
  
steps:
  ### Steps for Release Branches

  - label: "Release: Build App"
    agents: *macos
    branches: *release_branch
    env: *env
    commands:
      - *setup
      - bundle exec fastlane point_dependencies_to_pending_releases
      - *build_app

  ### Steps for Feature Branches

  - label: "Feature: Build App"
    agents: *macos
    branches: *feature_branch
    env: *env
    commands:
      - *setup
      - bundle exec fastlane point_dependencies_to_same_feature
      - *build_app
