steps:
  - label: ":eslint: JS Lint"
    command:
      - "yarn install"
      - "yarn lint:js"
    plugins:
      - docker#v3.0.1:
          image: "node:14-buster"
          mount-buildkite-agent: false

  - label: ":typescript: Types Lint"
    command:
      - "yarn install"
      - "yarn lint:types"
    plugins:
      - docker#v3.0.1:
          image: "node:14-buster"
          mount-buildkite-agent: false

  - label: ":hammer_and_wrench: Build"
    command:
      - "yarn install"
      - "yarn build"
    plugins:
      - docker#v3.0.1:
          image: "node:14-buster"
          mount-buildkite-agent: false

  - label: ":jest: Tests"
    agents:
      # We use a medium sized instance instead of the normal small ones because
      # jest likes our browserified bundle so much it OOMs.
      queue: "medium"
    command:
      - "yarn install"
      - "yarn build"
      - "yarn test"
    plugins:
      - docker#v3.0.1:
          image: "node:14-buster"
          mount-buildkite-agent: false

  - label: ":page_with_curl: Docs"
    command:
      - "yarn install"
      - "yarn gendoc"
    plugins:
      - docker#v3.0.1:
          image: "node:14-buster"
          mount-buildkite-agent: false

  - wait

  - label: ":horse: Trigger matrix-react-sdk"
    trigger: "matrix-react-sdk"
    branches: "develop"
    build:
        branch: "develop"
        message: "[js-sdk] ${BUILDKITE_MESSAGE}"
    async: true
