
version: '3.1'

services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: postgres
    command: -c fsync=off

  testenv:
    image: node:14
    depends_on:
      - postgres
    environment:
      SLACKBRIDGE_TEST_PGDB: "slackintegtest"
      SLACKBRIDGE_TEST_PGURL: "postgresql://postgres:postgres@postgres"
    working_dir: /app
    volumes:
      - ${BUILDKITE_BUILD_CHECKOUT_PATH}:/app