steps:
  - label: ":eslint: Lint"
    command:
      - "npm ci"
      - "npm run lint"
    plugins:
      - docker#v3.0.1:
          mount-buildkite-agent: false
          image: "node:14"

  - label: ":nodejs: 12 :mocha: Unit/Integration Test"
    command:
      - "npm ci"
      - "npm run build"
      - "npm run test"
    plugins:
      - docker#v3.0.1:
          mount-buildkite-agent: false
          image: "node:12"

  - label: ":nodejs: 14 :mocha: Unit/Integration Test"
    command:
      - "npm ci"
      - "npm run build"
      - "npm run test"
    plugins:
      - docker#v3.0.1:
          mount-buildkite-agent: false
          image: "node:14"

  - label: ":nodejs: 14 :postgres: 11 :mocha: Postgres Test"
    command:
      - "npm ci"
      - "npm run build"
      - "npm run test:postgres"
    plugins:
      - matrix-org/download#v1.1.0:
          urls:
            - https://raw.githubusercontent.com/matrix-org/pipelines/master/matrix-appservice-slack/docker-compose.postgres.yml
      - docker-compose#v3.2.0:
          run: testenv
          config:
            - /tmp/download-${BUILDKITE_BUILD_ID}/docker-compose.postgres.yml

  - label: ":newspaper: Newsfile"
    branches: "!master !develop !release-*"
    command:
      - "python3 -m pip install towncrier"
      - "python3 -m towncrier.check --compare-with=origin/develop"
    plugins:
      - docker#v3.0.1:
          image: "python:3.6"
          propagate-environment: true
          mount-buildkite-agent: false
