steps:
  - label: "Synapse - :python: 3.5 / SQLite / Monolith"
    agents:
      queue: "medium"
    command:
      - "mkdir -p /src"
      - "(wget -O - https://github.com/matrix-org/synapse/archive/$BUILDKITE_BRANCH.tar.gz || wget -O - https://github.com/matrix-org/synapse/archive/develop.tar.gz) | tar -xz --strip-components=1 -C /src/"
      - "cd /src/"
      - "bash /bootstrap.sh synapse"
    plugins:
      - docker#v3.0.1:
          image: "matrixdotorg/sytest-synapse:py35"
          propagate-environment: true
          always-pull: true
          workdir: "/sytest"
          entrypoint: '/bin/sh'
          shell: ["-x", "-c"]
          init: false
          mount-buildkite-agent: false
          # we mount the working copy read-only to make sure that it doesn't
          # modify local files (cf https://github.com/matrix-org/sytest/pull/748)
          mount-checkout: false
          volumes:
            - "./logs:/logs"
            - ".:/workdir:ro"
      - artifacts#v1.2.0:
          upload: [ "logs/**/*.log", "logs/**/*.log.*", "logs/results.tap" ]
      - matrix-org/annotate:
          path: "logs/annotate.md"
          style: "error"
    retry:
      automatic:
        - exit_status: -1
          limit: 2
        - exit_status: 2
          limit: 2

  - label: "Synapse - :python: 3.5 / :postgres: 9.6 / Monolith"
    agents:
      queue: "medium"
    env:
      POSTGRES: "1"
    command:
      - "mkdir -p /src"
      - "(wget -O - https://github.com/matrix-org/synapse/archive/$BUILDKITE_BRANCH.tar.gz || wget -O - https://github.com/matrix-org/synapse/archive/develop.tar.gz) | tar -xz --strip-components=1 -C /src/"
      - "cd /src/"
      - "bash /bootstrap.sh synapse"
    plugins:
      - docker#v3.0.1:
          image: "matrixdotorg/sytest-synapse:py35"
          propagate-environment: true
          always-pull: true
          workdir: "/sytest"
          entrypoint: '/bin/sh'
          shell: ["-x", "-c"]
          init: false
          mount-buildkite-agent: false
          mount-checkout: false
          volumes:
            - "./logs:/logs"
            - ".:/workdir:ro"
      - artifacts#v1.2.0:
          upload: [ "logs/**/*.log", "logs/**/*.log.*", "logs/results.tap" ]
      - matrix-org/annotate:
          path: "logs/annotate.md"
          style: "error"
    retry:
      automatic:
        - exit_status: -1
          limit: 2
        - exit_status: 2
          limit: 2

  - label: "Synapse - :python: 3.5 / :postgres: 9.6 / Workers"
    agents:
      queue: "medium"
    env:
      POSTGRES: "1"
      WORKERS: "1"
      BLACKLIST: "synapse-blacklist-with-workers"
    command:
      - "mkdir -p /src"
      - "(wget -O - https://github.com/matrix-org/synapse/archive/$BUILDKITE_BRANCH.tar.gz || wget -O - https://github.com/matrix-org/synapse/archive/develop.tar.gz) | tar -xz --strip-components=1 -C /src/"
      - "cd /src/"
      - "bash -c 'cat /src/sytest-blacklist /src/.buildkite/worker-blacklist > /src/synapse-blacklist-with-workers'"
      - "bash /bootstrap.sh synapse"
    plugins:
      - docker#v3.0.1:
          image: "matrixdotorg/sytest-synapse:py35"
          propagate-environment: true
          always-pull: true
          workdir: "/sytest"
          entrypoint: '/bin/sh'
          shell: ["-x", "-c"]
          init: false
          mount-buildkite-agent: false
          mount-checkout: false
          volumes:
            - "./logs:/logs"
            - ".:/workdir:ro"
      - artifacts#v1.2.0:
          upload: [ "logs/**/*.log", "logs/**/*.log.*", "logs/results.tap" ]
      - matrix-org/annotate:
          path: "logs/annotate.md"
          style: "error"
    retry:
      automatic:
        - exit_status: -1
          limit: 2
        - exit_status: 2
          limit: 2

  - label: "Synapse - :python: 3.7 / :postgres: 11 / Monolith"
    agents:
      queue: "medium"
    env:
      POSTGRES: "1"
    command:
      - "mkdir -p /src"
      - "(wget -O - https://github.com/matrix-org/synapse/archive/$BUILDKITE_BRANCH.tar.gz || wget -O - https://github.com/matrix-org/synapse/archive/develop.tar.gz) | tar -xz --strip-components=1 -C /src/"
      - "cd /src/"
      - "bash /bootstrap.sh synapse"
    plugins:
      - docker#v3.0.1:
          image: "matrixdotorg/sytest-synapse:py37"
          propagate-environment: true
          always-pull: true
          workdir: "/sytest"
          entrypoint: '/bin/sh'
          shell: ["-x", "-c"]
          init: false
          mount-buildkite-agent: false
          mount-checkout: false
          volumes:
            - "./logs:/logs"
            - ".:/workdir:ro"
      - artifacts#v1.2.0:
          upload: [ "logs/**/*.log", "logs/**/*.log.*", "logs/results.tap" ]
      - matrix-org/annotate:
          path: "logs/annotate.md"
          style: "error"
    retry:
      automatic:
        - exit_status: -1
          limit: 2
        - exit_status: 2
          limit: 2

  - label: "Synapse - :python: 3.7 / :postgres: 11 / Workers"
    agents:
      queue: "medium"
    env:
      POSTGRES: "1"
      WORKERS: "1"
      BLACKLIST: "synapse-blacklist-with-workers"
    command:
      - "mkdir -p /src"
      - "(wget -O - https://github.com/matrix-org/synapse/archive/$BUILDKITE_BRANCH.tar.gz || wget -O - https://github.com/matrix-org/synapse/archive/develop.tar.gz) | tar -xz --strip-components=1 -C /src/"
      - "cd /src/"
      - "bash -c 'cat /src/sytest-blacklist /src/.buildkite/worker-blacklist > /src/synapse-blacklist-with-workers'"
      - "bash /bootstrap.sh synapse"
    plugins:
      - docker#v3.0.1:
          image: "matrixdotorg/sytest-synapse:py37"
          propagate-environment: true
          always-pull: true
          workdir: "/sytest"
          entrypoint: '/bin/sh'
          shell: ["-x", "-c"]
          init: false
          mount-buildkite-agent: false
          mount-checkout: false
          volumes:
            - "./logs:/logs"
            - ".:/workdir:ro"
      - artifacts#v1.2.0:
          upload: [ "logs/**/*.log", "logs/**/*.log.*", "logs/results.tap" ]
      - matrix-org/annotate:
          path: "logs/annotate.md"
          style: "error"
    retry:
      automatic:
        - exit_status: -1
          limit: 2
        - exit_status: 2
          limit: 2
          
  - label: "Dendrite - :go: 1.11 / :postgres: 9.6"
    agents:
      queue: "medium"
    env:
      POSTGRES: "1"
    command:
      - "mkdir -p /src"
      - "(wget -O - https://github.com/matrix-org/dendrite/archive/$BUILDKITE_BRANCH.tar.gz || wget -O - https://github.com/matrix-org/dendrite/archive/master.tar.gz) | tar -xz --strip-components=1 -C /src/"
      - "cd /src/"
      - "bash /bootstrap.sh dendrite"
    plugins:
      - docker#v3.0.1:
          image: "matrixdotorg/sytest-dendrite"
          propagate-environment: true
          always-pull: true
          workdir: "/sytest"
          entrypoint: '/bin/sh'
          shell: ["-x", "-c"]
          init: false
          debug: true
          mount-buildkite-agent: false
          mount-checkout: false
          volumes:
            - "./logs:/logs"
            - ".:/workdir:ro"
      - artifacts#v1.2.0:
          upload: [ "logs/**/*.log", "logs/**/*.log.*", "logs/results.tap" ]
    soft_fail:
      - exit_status: 1
    retry:
      automatic:
        - exit_status: -1
          limit: 2
        - exit_status: 2
          limit: 2
