steps:
  - command:
      - go build -tags="*" ./internal/...
    label: "\U0001F528 Build Complement / :go: 1.13"
    plugins:
      - docker#v3.7.0:
          image: "golang:1.13"
          mount-buildkite-agent: false
    retry:
      automatic:
        - exit_status: 128
          limit: 3

  - command:
      - go build -tags="*" ./internal/...
    label: "\U0001F528 Build Complement / :go: 1.15"
    plugins:
      - docker#v3.7.0:
          image: "golang:1.15"
          mount-buildkite-agent: false
    retry:
      automatic:
        - exit_status: 128
          limit: 3

  - wait

  # Linting can take a while. Run it after the wait to not block the test suite runs
  - command:
      - ./build/scripts/find-lint.sh
    label: "\U0001F9F9 Lint / :go: 1.15"
    agents:
      # Use a larger instance as linting takes a lot of memory
      queue: "xlarge"
    plugins:
      - docker#v3.7.0:
          image: "golang:1.15"
          mount-buildkite-agent: false
    retry:
      automatic:
        - exit_status: 128
          limit: 3

  - command:
      # Build the Synapse for Complement docker image, which is located at:
      # https://github.com/matrix-org/complement/blob/master/dockerfiles/Synapse.Dockerfile.
      - docker build -t complement-synapse -f dockerfiles/Synapse.Dockerfile dockerfiles/
      # Run the tests!
      - COMPLEMENT_BASE_IMAGE=complement-synapse go test -v -tags "synapse_blacklist" ./tests
    label: "\U0001F9EA Complement / Synapse Monolith / :go: 1.15"
    agents:
      queue: "medium"
    plugins:
      - docker#v3.7.0:
          # The dockerfile for this image is at https://github.com/matrix-org/complement/blob/master/dockerfiles/ComplementCIBuildkite.Dockerfile.
          image: "matrixdotorg/complement:latest"
          mount-buildkite-agent: false
          # Complement needs to know if it is running under CI
          environment:
           - "CI=true"
          publish: [ "8448:8448" ]
          # Complement uses Docker so pass through the docker socket. This means Complement shares
          # the hosts Docker.
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
    retry:
      automatic:
        - exit_status: 128
          limit: 3

  - command:
      # Build the Dendrite for Complement docker image, which is located at:
      # https://github.com/matrix-org/complement/blob/master/dockerfiles/Dendrite.Dockerfile.
      - docker build -t complement-dendrite -f dockerfiles/Dendrite.Dockerfile .
      # Run the tests!
      - COMPLEMENT_BASE_IMAGE=complement-dendrite go test -v -tags "msc2836" ./tests
    label: "\U0001F9EA Complement / Dendrite Monolith / :go: 1.15"
    agents:
      queue: "medium"
    plugins:
      - docker#v3.7.0:
          # The dockerfile for this image is at https://github.com/matrix-org/complement/blob/master/dockerfiles/ComplementCIBuildkite.Dockerfile.
          image: "matrixdotorg/complement:latest"
          mount-buildkite-agent: false
          # Complement needs to know if it is running under CI
          environment:
           - "CI=true"
          publish: [ "8448:8448" ]
          # Complement uses Docker so pass through the docker socket. This means Complement shares
          # the hosts Docker.
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
    retry:
      automatic:
        - exit_status: 128
          limit: 3
