steps:
  - label: ":eslint: JS Lint"
    command:
      - "echo '--- Install'"
      - "yarn install --ignore-scripts"
      - "echo '+++ Lint'"
      - "yarn lint:js"
    plugins:
      - docker#v3.0.1:
          image: "node:14-buster"
          mount-buildkite-agent: false

  - label: ":eslint: Types Lint"
    command:
      # We fetch the develop js-sdk to get matching types etc.
      - "echo '--- Install js-sdk'"
      - "./scripts/ci/install-deps.sh --ignore-scripts"
      - "echo '+++ Lint'"
      - "yarn lint:types"
    plugins:
      - docker#v3.0.1:
          image: "node:14-buster"
          # This allows the test script to see what branch it's testing and check
          # out the equivalent dependency branches, if they exist
          propagate-environment: true
          mount-buildkite-agent: false

  - label: ":stylelint: Style Lint"
    command:
      - "echo '--- Install'"
      - "yarn install --ignore-scripts"
      - "yarn lint:style"
    plugins:
      - docker#v3.0.1:
          image: "node:14-buster"
          mount-buildkite-agent: false

  - label: ":jest: Tests"
    agents:
      # We use a medium sized instance instead of the normal small ones because
      # webpack loves to gorge itself on resources.
      queue: "medium"
    command:
      - "echo '--- Install js-sdk'"
      # We don't use the babel-ed output for anything so we can --ignore-scripts
      # to save transpiling the files. We run the transpile step explicitly in
      # the 'build' job.
      - "./scripts/ci/install-deps.sh --ignore-scripts"
      - "yarn run reskindex"
      - "echo '+++ Test'"
      - "yarn test"
    plugins:
      - docker#v3.0.1:
          image: "node:14-buster"
          # This allows the test script to see what branch it's testing and check
          # out the equivalent dependency branches, if they exist
          propagate-environment: true
          mount-buildkite-agent: false

  - label: ":hammer_and_wrench: Build"
    command:
      # We fetch the develop js-sdk to get matching types etc.
      - "echo '--- Install js-sdk'"
      - "./scripts/ci/install-deps.sh --ignore-scripts"
      - "echo '+++ Build'"
      - "yarn build"
    plugins:
      - docker#v3.0.1:
          image: "node:14-buster"
          # This allows the test script to see what branch it's testing and check
          # out the equivalent dependency branches, if they exist
          propagate-environment: true
          mount-buildkite-agent: false

  - label: ":chains: End-to-End Tests"
    agents:
      # We use a xlarge sized instance instead of the normal small ones because
      # e2e tests otherwise take +-8min
      queue: "xlarge"
    command:
      # `end-to-end-tests.sh` contains `echo` commands to mark sections
      - "./scripts/ci/end-to-end-tests.sh"
    plugins:
      - docker#v3.0.1:
          image: "vectorim/element-web-ci-e2etests-env:latest"
          # This allows the test script to see what branch it's testing and check
          # out the equivalent dependency branches, if they exist
          propagate-environment: true
          workdir: "/workdir/matrix-react-sdk"
          mount-buildkite-agent: false
    retry:
      automatic:
        - exit_status: 1 # retry end-to-end tests once as Puppeteer sometimes fails
          limit: 1
    artifact_paths:
      - "test/end-to-end-tests/logs/**/*"
      - "test/end-to-end-tests/synapse/installations/consent/homeserver.log"

  - label: ":wrench: Element Tests"
    agents:
      # We use a medium sized instance instead of the normal small ones because
      # webpack loves to gorge itself on resources.
      queue: "medium"
    command:
      - "echo '+++ Test'"
      - "./scripts/ci/app-tests.sh"
    plugins:
      - docker#v3.0.1:
          image: "node:14-buster"
          # This allows the test script to see what branch it's testing and check
          # out the equivalent dependency branches, if they exist
          propagate-environment: true
          workdir: "/workdir/matrix-react-sdk"
          mount-buildkite-agent: false

  - label: ":globe_with_meridians: i18n"
    command:
      - "echo '--- Install'"
      - "yarn install --ignore-scripts"
      - "echo '+++ Test'"
      - "yarn diff-i18n"
    plugins:
      - docker#v3.0.1:
          image: "node:14-buster"
          mount-buildkite-agent: false

  - wait

  - label: ":horse: Trigger element-web"
    trigger: "element-web"
    branches: "develop"
    build:
        branch: "develop"
        message: "[react-sdk] ${BUILDKITE_MESSAGE}"
    async: true
