steps:
  - label: ":eslint: Lint"
    command:
      - "npm ci"
      - "npm run-script lint"
    plugins:
      - docker#v3.0.1:
          image: "node:14"
          mount-buildkite-agent: false

  - label: ":jasmine: Tests Node 12"
    command:
      - "npm ci"
      - "npm run-script test"
    plugins:
      - docker#v3.0.1:
          image: "node:12"
          mount-buildkite-agent: false

  - label: ":jasmine: Tests Node 14"
    command:
      - "npm ci"
      - "npm run-script test"
    plugins:
      - docker#v3.0.1:
          image: "node:14"
          mount-buildkite-agent: false

  - label: ":jasmine: Tests Node 16"
    command:
      - "npm ci"
      - "npm run-script test"
    plugins:
      - docker#v3.0.1:
          image: "node:16"
          mount-buildkite-agent: false

  - label: ":nodejs: 14 :postgres: 11 :jasmine: Postgres Test"
    command:
      - "npm ci"
      - "npm run-script ci-test"
    plugins:
      - matrix-org/download#v1.1.0:
          urls:
            - https://raw.githubusercontent.com/matrix-org/pipelines/master/matrix-appservice-irc/docker-compose.postgres.yml
      - docker-compose#v3.2.0:
          run: testenv
          config:
            - /tmp/download-${BUILDKITE_BUILD_ID}/docker-compose.postgres.yml

  - label: ":nyc: Coverage"
    command:
      - "npm ci"
      - "npm run-script ci-test"
    plugins:
      - docker#v3.0.1:
          image: "node:14"
          mount-buildkite-agent: false

  - label: ":newspaper: Newsfile"
    branches: "!master !develop !release-*"
    command:
      - "./scripts/changelog-check.sh"
    plugins:
      - docker#v3.0.1:
          image: "python:3.6"
          mount-buildkite-agent: false
