steps:
  - label: ":eslint: Lint"
    command:
      - "npm install"
      - "npm run lint"
    plugins:
      - docker#v3.0.1:
          image: "node:12"
          mount-buildkite-agent: false

  - label: ":jasmine: Tests Node 10"
    command:
      - "npm install"
      - "npm run test"
    plugins:
      - docker#v3.0.1:
          image: "node:10"
          propagate-uid-gid: true # So NPM won't complain about permission issues
          mount-buildkite-agent: false
          debug: true

  - label: ":jasmine: Tests Node 12"
    command:
      - "npm install"
      - "npm run test"
    plugins:
      - docker#v3.0.1:
          image: "node:12"
          propagate-uid-gid: true
          mount-buildkite-agent: false
          debug: true

  - label: ":nyc: Coverage"
    command:
      - "npm install"
      - "npm run ci-test"
    plugins:
      - docker#v3.0.1:
          image: "node:12"
          propagate-uid-gid: true
          mount-buildkite-agent: false
          debug: true
