steps:
  - label: ":eslint: Lint"
    command:
      - "yarn"
      - "yarn lint"
    plugins:
      - docker#v3.0.1:
          image: "node:12"

  - label: ":jasmine: Tests Node 10"
    command:
      - "yarn"
      - "yarn test"
    plugins:
      - docker#v3.0.1:
          image: "node:10"

  - label: ":jasmine: Tests Node 12"
    command:
      - "yarn"
      - "yarn test"
    plugins:
      - docker#v3.0.1:
          image: "node:12"

  - label: ":nyc: Coverage"
    command:
      - "yarn"
      - "yarn ci-test"
    plugins:
      - docker#v3.0.1:
          image: "node:12"
