steps:
  - command:
      - "echo '--- Install towncrier'"
      - "pip install towncrier"
      - "echo '+++ Check newsfile'"
      - "python -m towncrier.check"
    label: ":rolled_up_newspaper: Newsfile"
    plugins:
      - docker#v3.0.1:
          image: "python:3.6"
    branches: "!master !release-*"

  - command:
      - "echo '--- Install dependencies'"
      - "pip install -e ."
      - "echo '+++ Run unit tests'"
      - "trial tests"
    label: ":partyparrot: Unit tests / :python: 2.7"
    plugins:
      - docker#v3.0.1:
          image: "python:2.7"
    artifact_paths:
      - "_trial_temp/test.log"

  - command:
      - "echo '--- Install dependencies'"
      - "pip install -e ."
      - "echo '--- Install matrix_is_tester'"
      - "pip install git+https://github.com/matrix-org/matrix-is-tester.git"
      - "echo '+++ Run Tests'"
      - "trial matrix_is_tester"
    label: ":pytest: matrix_is_tester / :python: 2.7"
    timeout_in_minutes: 5
    plugins:
      - docker#v3.0.1:
          image: "python:2.7"
    artifact_paths:
      - "matrix_is_test/sydent.stderr"
      - "_trial_temp/test.log"

  - command:
      - "echo '--- Install dependencies'"
      - "pip install -e ."
      - "echo '+++ Run unit tests'"
      - "trial tests"
    label: ":partyparrot: Unit tests / :python: 3.5"
    plugins:
      - docker#v3.0.1:
          image: "python:3.5"
    artifact_paths:
      - "_trial_temp/test.log"

  - command:
      - "echo '--- Install dependencies'"
      - "pip install -e ."
      - "echo '--- Install matrix_is_tester'"
      - "pip install git+https://github.com/matrix-org/matrix-is-tester.git"
      - "echo '+++ Run Tests'"
      - "trial matrix_is_tester"
    label: ":pytest: matrix_is_tester / :python: 3.5"
    timeout_in_minutes: 5
    plugins:
      - docker#v3.0.1:
          image: "python:3.5"
    artifact_paths:
      - "matrix_is_test/sydent.stderr"
      - "_trial_temp/test.log"

  - command:
      - "echo '--- Install dependencies'"
      - "pip install -e ."
      - "echo '+++ Run unit tests'"
      - "trial tests"
    label: ":partyparrot: Unit tests / :python: 3.8"
    plugins:
      - docker#v3.0.1:
          image: "python:3.8"
    artifact_paths:
      - "_trial_temp/test.log"

  - command:
      - "echo '--- Install dependencies'"
      - "pip install -e ."
      - "echo '--- Install matrix_is_tester'"
      - "pip install git+https://github.com/matrix-org/matrix-is-tester.git"
      - "echo '+++ Run Tests'"
      - "trial matrix_is_tester"
    label: ":pytest: matrix_is_tester / :python: 3.8"
    timeout_in_minutes: 5
    plugins:
      - docker#v3.0.1:
          image: "python:3.8"
    artifact_paths:
      - "matrix_is_test/sydent.stderr"
      - "_trial_temp/test.log"
