steps:
  - command:
      - "go version"
      - "go test ./..."
    label: "\U0001F9EA Unit tests / :go: 1.13"
    plugins:
      - docker#v3.0.1:
          image: "golang:1.13"
          mount-buildkite-agent: false

  - command:
      - "go version"
      - "golangci-lint run"
    label: "\U0001F9F9 Lint / :go: 1.13"
    agents:
      queue: "medium"
    plugins:
      - docker#v3.0.1:
          image: "golang:1.13"
          mount-buildkite-agent: false
